version: '3.5'  

services:
  frontend:
    image: part2-7/frontend
    build: 
        context: https://github.com/docker-hy/ml-kurkkumopo-frontend.git
    ports:
        - "3000:3000"
    container_name: ml-frontend

  backend:
    image: part2-7/backend
    build:
        context: https://github.com/docker-hy/ml-kurkkumopo-backend.git
    ports:
        - "5000:5000"
    expose:
        - "5000"
    container_name: ml-backend
    volumes:
      - model:/src/model
    depends_on:
      - training

  training:
    image: part2-7/training
    build:
        context: https://github.com/docker-hy/ml-kurkkumopo-training.git
    container_name: ml-training
    volumes:
      - images:/src/imgs
      - model:/src/model

volumes:
  model:
  images: